Update doc
AgoraIO-Extensions/Agora-Flutter-SDK pull request #756
Opened 2022-09-09 14:32 UTC by littleGnAl

Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

2022-09-12 10:30 UTC, maxxfrazer commented on lib/src/agora_base.dart
> +  /// This interface class is deprecated.
@Deprecated annotation should be used for this.

2022-09-12 10:30 UTC, maxxfrazer commented on lib/src/agora_media_player.dart
> +  /// This method is called asynchronously.If you need to play a media file, make sure you receive the onPlayerSourceStateChanged callback reporting playerStateOpenCompleted before calling the play m
This space should not have been deleted

2022-09-12 10:31 UTC, maxxfrazer commented on lib/src/agora_media_player.dart
> +  /// This method is called asynchronously.If you need to play a media file, make sure you receive the onPlayerSourceStateChanged callback reporting playerStateOpenCompleted before calling the play m
This space should not have been deleted

2022-09-12 10:32 UTC, maxxfrazer commented on lib/src/agora_rtc_engine.dart
> +  /// The user role. See ClientRoleType .
Should "for details" be removed? If so, the trailing space should also.

2022-09-12 10:32 UTC, maxxfrazer commented on lib/src/agora_rtc_engine.dart
> +  /// Releases the instanceRtcEngine.
looks like a mistake

2022-09-12 10:32 UTC, maxxfrazer commented on lib/src/agora_rtc_engine.dart
> +  /// * [null] The sample rate (Hz) of the audio data, which can be set as 8000, 16000, 32000, 44100, or 48000.
probably shouldn't be null

2022-09-12 10:33 UTC, maxxfrazer requested changes
Most of these doc changes look incorrect.

2022-09-15 02:38 UTC, littleGnAl commented
@maxxfrazer This is a test PR by the bot, I'll close it, sorry about that.

2022-09-15 02:38 UTC, closed without merging